### ISSUE TITLE
Is there a maven release?

### ISSUE THREAD

**Issue by vshank77** [stoyanr/Evictor#1]
Hi.

I see that your POM is written to deploy the artifact to Maven central repo and I have seen that you have actually released another library called Mastermind there.

Is there a plan to release this one? We can push the library to our internal Nexus repo, but I think it will be largely beneficial if this project was released to the central repo.

Let me know if you need any help?

Cheers
Shankar

**Comment by trecloux** [comment]
I am also interested in a maven central release

**Comment by arunaugustine** [comment]
Me too. If I can help you with this, I would be happy to.

**Comment by iwhitfield** [comment]
+1

**Comment by pjfila** [comment]
+1

**Comment by kalvasunil** [comment]
+1

**Comment by stoyanr** [comment]
Evictor 1.0.0 is released to Maven Central now, see https://oss.sonatype.org/content/repositories/releases/com/stoyanr/evictor/1.0.0/. Thanks to @sangupta for the numerous improvements he contributed and for giving me the last bit of motivation for releasing.
