### ISSUE TITLE
Does the library is still maintained ?

### ISSUE THREAD

**Issue by jukedom** [stoyanr/Evictor#4]
Hello,

We have identified that this library is used by the following spring module "spring-cloud-starter-loadbalancer".
We would like to know if the evictor library is still maintained, as there are no commit for about 5 years.

Thanks.
Regards,
Dominique

**Comment by stoyanr** [comment]
@dominiquemongelli Well, I am still around, but there haven't been any requests, issues, or PRs in the last 5 years, so nothing for me to do. Do you have something specific in mind?

**Comment by jukedom** [comment]
Hi @stoyanr, thanks for the answer. the question was more about potential security risks. We just wanted to make sure that if critical vulnerabilities are raised, it will be fixed.

**Comment by stoyanr** [comment]
@dominiquemongelli I won't do it proactively (I won't check), but if an issue is raised for a concrete issue or updating a dependency, I will address it.

**Comment by jukedom** [comment]
@stoyanr Ok, sounds good. Thanks. I close the ticket.
